fix: update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,4 +11,4 @@ jobs:
 
     steps:
       - name: Send HTTP Request
-        run: curl -f https://${{ secrets.DOMAIN_NAME }}/api/etc/supabase-activity-scheduler || echo "Request failed"
+        run: curl -f https://${{ secrets.DOMAIN_NAME }}/api/supabase-activity-scheduler || echo "Request failed"
